'use client';

import { useState } from 'react';

export default function MongoTestPage() {
  const [loading, setLoading] = useState(false);
  const [res, setRes] = useState('');

  const sendTestData = async () => {
    setLoading(true);
    setRes('');

    const response = await fetch('/api/save-to-mongo', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        user_id: 'test-user-123',
        job_title: 'Frontend Developer',
        ai_summary: 'A smart summary generated by AI.',
        created_at: new Date(),
      }),
    });

    const data = await response.json();
    setRes(JSON.stringify(data, null, 2));
    setLoading(false);
  };

  return (
    <div className="p-4">
      <h1 className="text-xl font-bold mb-4">MongoDB Test Page</h1>
      <button
        onClick={sendTestData}
        className="bg-blue-600 text-white px-4 py-2 rounded"
        disabled={loading}
      >
        {loading ? 'Sending...' : 'Send Test Data to MongoDB'}
      </button>
      {res && (
        <pre className="mt-4 bg-gray-100 p-2 rounded text-sm whitespace-pre-wrap">
          {res}
        </pre>
      )}
    </div>
  );
}
