const urduDict = {
  "JavaScript": "جاوا اسکرپٹ",
  "is": "ہے",
  "a": "ایک",
  "versatile": "ہمہ گیر",
  "programming language": "پروگرامنگ زبان",
  "used on the web": "ویب پر استعمال ہوتی ہے",
  "used": "استعمال ہوتی ہے",
  "on the web": "ویب پر",
  "on": "پر",
  "the web": "ویب",
  "It": "یہ",
  "allows": "اجازت دیتا ہے",
  "developers": "ڈویلپرز",
  "to build": "تعمیر کرنے کے لیے",
  "build": "بنائیں",
  "dynamic": "متحرک",
  "and": "اور",
  "interactive": "انٹرایکٹو",
  "web applications": "ویب ایپلیکیشنز",
  "easily": "آسانی سے",
  "React": "ری ایکٹ",
  "webpage": "ویب صفحہ",
  "stylesheet": "سٹائل شیٹ",
  "browser": "براؤزر",
  "font": "فونٹ",
  "loaded": "لوڈ",
  "custom": "حسب ضرورت",
  "interactive": "انٹرایکٹو",
  "dynamic": "متحرک",
  "download": "ڈاؤن لوڈ",
  "user interface": "صارف انٹرفیس",
  "summary": "خلاصہ",
  "CSS": "سی ایس ایس",
  "function": "فنکشن",
  "component": "کمپوننٹ",
  "state": "حالت",
  "effect": "اثر",
  "hook": "ہک",
  "reference": "حوالہ",
  "asynchronous": "غیر ہموار",
  "execution": "عملدرآمد",
  "data": "ڈیٹا",
  "variables": "ویری ایبلز",
  "performance": "کارکردگی",
  "speed": "رفتار",
  "load time": "لوڈ وقت",
  "render": "رینڈر",
  "promise": "وعدہ",
  "callback": "کال بیک",
  "DOM": "ڈی او ایم",
  "guide": "رہنمائی",
  "example": "مثال",
  "development": "ترقی",
  "frontend": "فرنٹ اینڈ",
  "backend": "بیک اینڈ",
  "open-source": "اوپن سورس",
  "article": "مضمون",
  "developer": "ڈویلپر",
  "web development": "ویب ڈویلپمنٹ",
  "ARTICLES": "مضامین",
  "NOTES": "نوٹس",
  "LINKS": "روابط",
  "GUIDES": "رہنمائیاں",
  "ALMANAC": "المانک",
  "PICKS": "انتخاب",
  "SHUFFLE": "شفل",
  "Search": "تلاش",
  "HOME": "ہوم",
  "Layout": "لے آؤٹ",
  "comprehensive": "جامع",
  "focusing": "توجہ دیتی ہے",
  "settings": "ترتیبات",
  "parent container": "پیرنٹ کنٹینر",
  "child elements": "چائلڈ عناصر",
  "Table of contents": "فہرست مضامین",
  "Introduction": "تعارف",
  "Basics": "بنیادی نکات",
  "Important Terminology": "اہم اصطلاحات",
  "Grid Properties": "گرڈ کی خصوصیات",
  "Special Units & Functions": "خصوصی یونٹس اور فنکشنز",
  "Browser Support": "براؤزر سپورٹ",
  "Fluid Columns": "فلوئیڈ کالمز",
  "Snippet": "کوڈ اسنیپٹ",
  "Animation": "انیمیشن",
  "Tricks": "ٹرکس",
  "Learning": "سیکھنا",
  "Videos": "ویڈیوز",
  "More Sources": "مزید ذرائع",
  "poster": "پوسٹر",
  "Reference": "حوالہ",
  "a lot": "اکثر",
  "high-res image": "ہائی ریز تصویر",
  "you can print": "آپ پرنٹ کر سکتے ہیں",
  "FREE": "مفت",
  "Parent": "والدین",
  "Grid Container": "گرڈ کنٹینر",
  "Jump links": "جمپ لنکس",
  "display": "ڈسپلے",
  "Defines": "متعین کرتا ہے",
  "element": "عنصر",
  "establishes": "قائم کرتا ہے",
  "new": "نیا",
  "formatting context": "فارمیٹنگ سیاق و سباق",
  "for its contents": "اس کے مواد کے لیے",
 
  // Common phrases
  "What It Is and How it Works": "یہ کیا ہے اور کیسے کام کرتا ہے",
  "How to Focus and Increase Your Attention Span": "کیسے توجہ مرکوز کریں اور اپنی توجہ کی مدت بڑھائیں",
  "Mind-Hacks": "ذہنی چالیں",
  "All Articles": "تمام مضامین",

   "JavaScript": "جاوا اسکرپٹ",
  "React": "ری ایکٹ",
  "CSS": "سی ایس ایس",
  "HTML": "ایچ ٹی ایم ایل",
  "function": "فنکشن",
  "component": "کمپوننٹ",
  "state": "حالت",
  "hook": "ہک",
  "effect": "اثر",
  "DOM": "ڈی او ایم",
  "variables": "ویری ایبلز",
  "asynchronous": "غیر ہم وقت",
  "execution": "عملدرآمد",
  "performance": "کارکردگی",
  "speed": "رفتار",
  "load time": "لوڈ وقت",
  "render": "رینڈر",
  "callback": "کال بیک",
  "reference": "حوالہ",

  // Blog & Article Structure
  "Articles": "مضامین",
  "Notes": "نوٹس",
  "Links": "روابط",
  "Guides": "رہنمائیاں",
  "Almanac": "المانک",
  "Picks": "انتخاب",
  "Shuffle": "شفل",
  "Search": "تلاش",
  "Home": "ہوم",
  "Table of contents": "فہرست مضامین",
  "poster": "پوسٹر",

  // Content Sections
  "Books": "کتابیں",
  "Newsletter": "نیوزلیٹر",
  "App": "ایپ",
  "Speaking": "تقاریر",
  "About": "تعارف",
  "Archives": "محفوظ شدہ مواد",
  "Podcast": "پوڈکاسٹ",

  // Typography & Layout
  "webpage": "ویب صفحہ",
  "stylesheet": "سٹائل شیٹ",
  "font": "فونٹ",
  "custom fonts": "حسب ضرورت فونٹس",
  "download the font": "فونٹ ڈاؤن لوڈ کریں",
  "display it": "اسے ظاہر کریں",
  "Layout": "لے آؤٹ",

  // Grid & UI
  "Grid Container": "گرڈ کنٹینر",
  "child elements": "چائلڈ عناصر",
  "display": "ڈسپلے",
  "element": "عنصر",
  "defines": "متعین کرتا ہے",
  "establishes": "قائم کرتا ہے",
  "formatting context": "فارمیٹنگ سیاق و سباق",

  // Learning Topics
  "Introduction": "تعارف",
  "Basics": "بنیادی نکات",
  "Important Terminology": "اہم اصطلاحات",
  "Grid Properties": "گرڈ کی خصوصیات",
  "Special Units & Functions": "خصوصی یونٹس اور فنکشنز",
  "Browser Support": "براؤزر سپورٹ",
  "Fluid Columns": "فلوئیڈ کالمز",
  "Snippet": "اسنیپٹ",
  "Animation": "انیمیشن",
  "Tricks": "چالیں",
  "Learning": "سیکھنا",
  "Videos": "ویڈیوز",
  "More Sources": "مزید ذرائع",

  // Atomic Habits
  "Atomic Habits Summary": "ایٹامک ہیبٹس کا خلاصہ",
  "Atomic Habits": "ایٹامک ہیبٹس",
  "in Three Sentences": "تین جملوں میں",
  "comprehensive, practical guide": "جامع اور عملی رہنمائی",
  "1% better every day": "ہر دن 1 فیصد بہتر",
  "change your habits": "اپنی عادتیں بدلیں",
  "good habits": "اچھی عادتیں",
  "bad habits": "بری عادتیں",
  "behavior change": "رویہ میں تبدیلی",
  "framework": "فریم ورک",
  "four laws": "چار قوانین",
  "simple set of rules": "سادہ اصولوں کا مجموعہ",

  // Motivation & Mindfulness
  "life-changing": "زندگی بدل دینے والا",
  "purpose": "مقصد",
  "impact": "اثر",
  "breathe": "سانس لینا",
  "think": "سوچنا",
  "enjoy": "لطف اندوز ہونا",
  "love": "محبت کرنا",
  "morning": "صبح",
  "lovely": "خوبصورت",
  "precious": "قیمتی",
  "privilege": "اعزاز",
  "alive": "زندہ",
  "starting to seep in": "داخل ہو رہی ہے",
  "early morning light": "صبح کی ہلکی روشنی",
  "wake up": "جاگنا",
  "Create a Lovely Morning": "ایک خوبصورت صبح کا آغاز کریں",

  // Productivity & Focus
  "Productivity": "پیداواریت",
  "focus": "توجہ",
  "concentration": "ارتکاز",
  "attention span": "توجہ کی مدت",
  "inspiration": "ترغیب",
  "tactical advice": "عملی مشورے",
  "useful": "مفید",
  "goals": "مقاصد",
  "collaboration": "تعاون",
  "time management": "وقت کا انتظام",
  "Remote Work": "ریموٹ ورک",
  "Join over 170K readers": "1 لاکھ 70 ہزار سے زائد قارئین میں شامل ہوں",
  "start their month with the newsletter": "ہر مہینے کا آغاز نیوزلیٹر سے کرتے ہیں",

  // Utility
  "yes": "جی ہاں",
  "no": "نہیں",
  "free": "مفت",
  "download": "ڈاؤن لوڈ",
  "page": "صفحہ",
  "not found": "نہیں ملا",
  "Sorry, this page isn’t available.": "معذرت، یہ صفحہ دستیاب نہیں ہے",
  "The link you followed may be broken": "شاید لنک خراب ہو گیا ہے",
  "or the page may have been removed": "یا صفحہ ہٹا دیا گیا ہے"

};




export function translateToUrdu(text) {
  let translated = text;

  Object.keys(urduDict).forEach((key) => {
    const regex = new RegExp(`\\b${key}\\b`, "gi");
    translated = translated.replace(regex, urduDict[key]);
  });

  // Optional: replace final period with Urdu full stop
  translated = translated.replace(/\.$/, "۔");

  return translated;
}
